const Menu = [
  {
    id: 1,
    name: "Chhola",
    imagesrc: "pics/chhola.jpg",
    category: "breakfast",
    price: "₹12",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 2,
    name: "Allu Pakoda",
    imagesrc: "pics/allu_pakoda.jpeg",
    category: "evening",
    price: "₹20",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 3,
    name: "Maiggi",
    imagesrc: "pics/maigi.jpeg",
    category: "lunch",
    price: "₹40",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 4,
    name: "Non Veg Thali",
    imagesrc: "pics/non_veg_thali.webp",
    category: "dinner",
    price: "₹200",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 5,
    name: "Chinese Food",
    imagesrc: "pics/chinese.jpg",
    category: "breakfast",
    price: "₹100",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 6,
    name: "Rajma Chawal",
    imagesrc: "pics/rajma rice.jpg",
    category: "dinner",
    price: "₹150",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 7,
    name: "Samosa",
    imagesrc: "pics/samosa.jpg",
    category: "evening",
    price: "₹50",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 8,
    name: "Corn",
    imagesrc: "pics/corn.jpeg",
    category: "lunch",
    price: "₹30",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 9,
    name: "Veg Thali",
    imagesrc: "pics/vegthali.jpg",
    category: "dinner",
    price: "₹300",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 10,
    name: "Pizza",
    imagesrc: "pics/pizza.jpeg",
    category: "evening",
    price: "₹250",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 11,
    name: "Dry Food",
    imagesrc: "pics/dryfood.jpeg",
    category: "lunch",
    price: "₹400",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
  {
    id: 12,
    name: "Sweets",
    imagesrc: "pics/sweets1.jpg",
    category: "breakfast",
    price: "₹60",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
  },
];

export default Menu;
